parameters:
    coreshop.form.type.user.validation_groups: [coreshop]

services:
    _defaults:
        public: true

    CoreShop\Bundle\UserBundle\Form\Type\ChangePasswordType:
        tags:
            - { name: form.type }

    CoreShop\Bundle\UserBundle\Form\Type\RequestResetPasswordType:
        tags:
            - { name: form.type }

    CoreShop\Bundle\UserBundle\Form\Type\ResetPasswordType:
        tags:
            - { name: form.type }
