CoreShop\Component\User\Model\User:
    getters:
        plainPassword:
            - NotBlank: { groups: [coreshop] }

    constraints:
        - \CoreShop\Bundle\ResourceBundle\Validator\Constraints\UniqueEntity:
              groups: ['coreshop']
              fields: ['email']
              values: {}
              message: 'coreshop.form.customer.email.unique'
              allowSameEntity: true
